path_to_scan = ""
ignore_these_exact_paths = []
any_part_of_path_to_ignore = [".git", "RECYCLE", "System"]

[logging]
console_logging_level = "DEBUG"
file_logging_level = "DEBUG"
logs_folder_path = "Logs"
use_logs_folder = true
number_of_logs_to_keep = 10
log_message_format = "%(asctime)s.%(msecs)03d %(levelname)s [%(funcName)s]: %(message)s"